# Generated by Django 3.2 on 2021-05-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('publication', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=25)),
                ('date', models.DateField(max_length=25)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
            ],
        ),
    ]
