# Generated by Django 3.2 on 2021-05-14 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestnews_site', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 2, 45, 50, 695115), max_length=25),
        ),
    ]
