# Generated by Django 3.2 on 2021-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestnews_site', '0004_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
